worker-threads: 4
worker-fs-threads: 2

logger-level: info

bot-token: your-bot-token
bot-token#env: BOT_TOKEN

server-port: 8080

stack_size: 1048576

pg-connection: postgresql://testsuite@localhost:15433/telegram_bot_db_1
