worker-threads: 4
worker-fs-threads: 2

logger-level: info

bot-token: your-bot-token
bot-token#env: BOT_TOKEN
bot-webhook-url: ""
bot-webhook-url#env: BOT_WEBHOOK_URL
bot-webhook-secret-token: ""
bot-webhook-secret-token#env: BOT_WEBHOOK_SECRET_TOKEN

server-port: 8080

stack_size: 1048576

pg-connection: postgresql://testsuite@localhost:15434/telegram_bot_db_1
